"""Add scheduling tables and coach shifts

Revision ID: 6e8d92bd331b
Revises: 
Create Date: 2025-10-15 18:04:23.361371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e8d92bd331b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('AB', 'ABC', 'PPL', 'FIVE_DAY', name='plantype'), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('assigned_coach_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='unique_client_plan')
    )
    op.create_index(op.f('ix_client_plans_id'), 'client_plans', ['id'], unique=False)
    op.create_table('client_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('preferred_start_hour', sa.Integer(), nullable=True),
    sa.Column('preferred_end_hour', sa.Integer(), nullable=True),
    sa.Column('is_flexible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='unique_client_prefs')
    )
    op.create_index(op.f('ix_client_preferences_id'), 'client_preferences', ['id'], unique=False)
    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', 'start_hour', 'coach_id', name='unique_slot')
    )
    op.create_index(op.f('ix_schedule_slots_id'), 'schedule_slots', ['id'], unique=False)
    op.add_column('bookings', sa.Column('slot_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('ai_generated', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'schedule_slots', ['slot_id'], ['id'])
    op.alter_column('payments', 'plan_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'CUSTOM'"))
    op.alter_column('payments', 'plan_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Custom'"))
    op.drop_index(op.f('idx_payments_paypal_capture_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_paypal_order_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_stripe_session_id'), table_name='payments')
    op.drop_index(op.f('stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('stripe_session_id'), table_name='payments')
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'stripe_session_id')
    op.add_column('users', sa.Column('shift_start_hour', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('shift_end_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shift_end_hour')
    op.drop_column('users', 'shift_start_hour')
    op.add_column('payments', sa.Column('stripe_session_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    op.create_index(op.f('stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('idx_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=False)
    op.create_index(op.f('idx_payments_paypal_order_id'), 'payments', ['paypal_order_id'], unique=False)
    op.create_index(op.f('idx_payments_paypal_capture_id'), 'payments', ['paypal_capture_id'], unique=False)
    op.alter_column('payments', 'plan_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Custom'"))
    op.alter_column('payments', 'plan_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'CUSTOM'"))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'ai_generated')
    op.drop_column('bookings', 'slot_id')
    op.drop_index(op.f('ix_schedule_slots_id'), table_name='schedule_slots')
    op.drop_table('schedule_slots')
    op.drop_index(op.f('ix_client_preferences_id'), table_name='client_preferences')
    op.drop_table('client_preferences')
    op.drop_index(op.f('ix_client_plans_id'), table_name='client_plans')
    op.drop_table('client_plans')
    # ### end Alembic commands ###
